#!/bin/sh
SNAP_BIN="/snap/bin/$(basename "$0")"
if [ ! -f "${SNAP_BIN}" ]; then
    if [ ! -w "/run/lxd-installer.socket" ]; then
      echo "Unable to trigger the installation of the LXD snap." >&2
      echo "Please make sure you're a member of the 'lxd' system group." >&2
      exit 1
    fi

    echo "Installing LXD snap, please be patient."
    python3 -c 'import socket; s=socket.socket(socket.AF_UNIX); s.connect("/run/lxd-installer.socket"); s.send(b"x"); s.recv(1)'

    for _ in $(seq 90); do
      sleep 1
      [ -x "${SNAP_BIN}" ] && break
    done
fi
exec "$SNAP_BIN" "$@"
